name: React Native Build

on:
  push:
    tags:
      - build-*

jobs:
  build:
    name: Build React Native
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configuração do Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # ajuste conforme sua necessidade

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn  # Cache para Yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Instalar dependências com Yarn
      run: yarn install --frozen-lockfile

    - name: Realizar o build (Aqui você pode adicionar os passos para realizar o build do seu app)
      run: |
        # Comandos para fazer o build do seu projeto React Native.
