name: React Native Build

on:
  push:
    tags:
      - build-*

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn  # Cache para Yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Instalar dependências com Yarn
      run: yarn install --frozen-lockfile

    - name: Run Tests
      run: yarn test

  build:
    name: Build React Native
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configuração do Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # ajuste conforme sua necessidade

    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Build on EAS
      run: eas build --platform android --non-interactive --no-wait
